repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.270
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        exclude: ^test/
-   repo: local
    hooks:
    -   id: pypi_readme
        name: PyPI README
        entry: python3 assets/make_pypi_readme.py
        language: system
        files: ^README\.md$
