site_name: arguably
site_description: The best Python CLI library, arguably.
strict: true
site_url: https://treykeown.github.io/arguably/


theme:
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: green
    accent: green
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: green
    accent: green
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - announce.dismiss
    - navigation.footer
    - navigation.expand
  logo: images/arguably_small.png
  favicon: images/arguably_tiny.png


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js
  - scripts/extra.js
extra_css:
  - styles/extra.css


repo_name: treykeown/arguably
repo_url: https://github.com/treykeown/arguably
edit_uri: edit/main/docs/


plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          filters: ["!^_"]
          docstring_options:
            ignore_init_summary: true
          separate_signature: true
          merge_init_into_class: true
          show_submodules: true
          show_object_full_path: true
          members_order: source
          group_by_category: false
          line_length: 80
          signature_crossrefs: true
          show_root_toc_entry: false
          show_source: false
          show_bases: true
          heading_level: 3


nav:
  - Home: index.md
  - Examples: examples.md
  - Tutorial:
    - Introduction: tutorial/intro.md
    - Subcommands: tutorial/subcommands.md
    - Type Hints: tutorial/type-hints.md
  - API Reference: api-reference.md
  - Contributing: contributing.md


markdown_extensions:
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.extra
