[tool.poetry]
name = "noarg"
version = "1.0.0"
description = "no arg(parse) - automatically turns functions into command line interfaces"
authors = ["Trey Keown <trey@keown.io>"]
readme = "README.md"
homepage = "https://github.com/jfktrey/noarg"
repository = "https://github.com/jfktrey/noarg"

[tool.poetry.dependencies]
python = "^3.9"
docstring-parser = "^0.15"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"
ruff = "^0.0.263"
pre-commit = "^3.3.2"
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
pytest-randomly = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.mypy]
disallow_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true

[tool.black]
line-length = 120

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]
